--Create table
CREATE TABLE users (
id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
email varchar(40) NOT NULL,
username varchar(80) NOT NULL,
password_hash varchar(100) NOT NULL
);

--Quer the informations in the table
SELECT * FROM users;

--Insert infos into table

INSERT INTO users
 (hospital_registration_number, email, hospital_name, password_hash)
 VALUES
 ('123', '123', 'HS', 'aa'),
 ('112', '122', 'HH', 'bb');