import Head from 'next/head';
import Layout from '../Components/Layout';

type Props = {
  username?: string;
};

export default function About(props: Props) {
  return (
    <div>
      <Head>
        <title>App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout username={props.username} />
    </div>
  );
}

export async function getServerSideProps() {
  const { getUsers } = await import('../util/database');
  const users = await getUsers();
  return {
    props: {
      users: users,
    },
  };
}
