import Head from 'next/head';
import Layout from '../Components/Layout';

type Props = {
  username?: string;
};

export default function Home(props: Props) {
  return (
    <div>
      <Head>
        <title>App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout username={props.username} />
      <div className="square"></div>
      <div className="hero-text">
        <h1 className="home-text">
          Find your desired shift in Health Care to work whenever you like
        </h1>
        <button className="find-job">Find Shifts</button>
      </div>

      <img className="hero" src="/hero.png" alt="hero"></img>
    </div>
  );
}
