import Head from 'next/head';
import Link from 'next/link';
import React, { useState } from 'react';
import Layout from '../Components/Layout';

type Props = {
  username?: string;
};

export default function Home(props: Props) {
  const [modal, setModal] = useState(false);

  const toggle = () => setModal(!modal);
  return (
    <div>
      <Head>
        <title>App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout username={props.username} />
      <div className="square"></div>
      <div className="hero-text">
        <h1 className="home-text">The platform for substitute doctors</h1>
        <p className="hero-par">
          We are the leading French job platform for medical personnel in
          substitute roles across specialties
        </p>
        <Link href="/jobs">
          <a>
            <button className="find-job">Find Job</button>
          </a>
        </Link>
        <span>
          {' '}
          {props.username ? (
            <Link href="/jobs">
              <a>
                <button className="find-job">Post Job</button>
              </a>
            </Link>
          ) : (
            <Link href="/login">
              <a>
                <button className="find-job">Post Job</button>
              </a>
            </Link>
          )}
        </span>
      </div>
      {
        // eslint-disable-next-line @next/next/no-img-element
        <img className="hero" src="/hero.png" alt="hero"></img>
      }
      {
        // eslint-disable-next-line @next/next/no-img-element
        <img className="hero-dots" src="/dotss.png" alt="hero"></img>
      }
    </div>
  );
}
