import Head from 'next/head';
import Layout from '../Components/Layout';

export default function Jobs(props) {
  return (
    <div>
      <Head>
        <title>{props.username}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout username={props.username} />
      <div className="jobs-page">
        <h1>Job Board</h1>
        <h2>My Posts</h2>
        <button>Add Shift</button>
      </div>
      <div></div>
    </div>
  );
}
