import 'react-quill/dist/quill.snow.css';
import dynamic from 'next/dynamic';
import Head from 'next/head';
import { useRouter } from 'next/router';
import Layout from '../../Components/Layout';
import {
  deleteJobByJobId,
  getEmailByJobId,
  getJobByJobId,
} from '../../util/database';

const ReactQuill = dynamic(() => import('react-quill'), { ssr: false });

export default function SingleJob(props: any) {
  const router = useRouter();
  async function deleteJobByJobI(id: any) {
    await fetch(`http://localhost:3000/api/jobs/${props.job.id}`, {
      method: 'DELETE',
    });
    router.push(`/jobs`);
  }
  let email = props.email.email;
  let text = props.job.details;
  return (
    <>
      <Head>
        <title>{props.username}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout username={props.username} />
      <div className="job-page">
        <h3>{props.job.title}</h3>
        <p>{}</p>
        <div
          dangerouslySetInnerHTML={{ __html: text }}
          className="container-sm"
        ></div>
        <span>
          {props.username ? (
            <button onClick={() => deleteJobByJobI(props.job.id)}>
              Delete
            </button>
          ) : (
            <a href={`mailto:${email}`}>Email Us</a>
          )}
        </span>
      </div>
    </>
  );
}

export async function getServerSideProps(context: any) {
  let jobid = context.query.jobId;
  const job = await getJobByJobId(jobid);
  const email = await getEmailByJobId(jobid);

  console.log('job', job);
  return {
    props: {
      job: job,
      email: email || null,
    },
  };
}
